# Stack metadata
STACK_PROFILE={{STACK_PROFILE}}
STACK_SOURCE_ROOT={{STACK_SOURCE_ROOT}}
STACK_INITDB_DIR={{STACK_INITDB_DIR}}
STACK_POSTGRES_DATA_DIR={{STACK_POSTGRES_DATA_DIR}}
STACK_REDIS_DATA_DIR={{STACK_REDIS_DATA_DIR}}
STACK_MINIFLUX_DATA_DIR={{STACK_MINIFLUX_DATA_DIR}}
STACK_HALO_DATA_DIR={{STACK_HALO_DATA_DIR}}
STACK_FLUXDIGEST_DATA_DIR={{STACK_FLUXDIGEST_DATA_DIR}}
STACK_FLUXDIGEST_OUTPUT_DIR={{STACK_FLUXDIGEST_OUTPUT_DIR}}
STACK_LOG_DIR={{STACK_LOG_DIR}}

# Proxy passthrough
http_proxy={{http_proxy}}
https_proxy={{https_proxy}}
HTTP_PROXY={{HTTP_PROXY}}
HTTPS_PROXY={{HTTPS_PROXY}}
GOPROXY={{GOPROXY}}
GOSUMDB={{GOSUMDB}}

# FluxDigest HTTP
APP_HTTP_PORT={{APP_HTTP_PORT}}

# FluxDigest runtime
APP_DATABASE_NAME={{FLUXDIGEST_DB_NAME}}
APP_DATABASE_USER={{FLUXDIGEST_DB_USER}}
APP_DATABASE_PASSWORD={{FLUXDIGEST_DB_PASSWORD}}
APP_DATABASE_DSN={{APP_DATABASE_DSN}}
APP_REDIS_ADDR={{APP_REDIS_ADDR}}
APP_JOB_API_KEY={{APP_JOB_API_KEY}}
APP_JOB_QUEUE={{APP_JOB_QUEUE}}
APP_WORKER_CONCURRENCY={{APP_WORKER_CONCURRENCY}}

# Security / admin bootstrap
APP_ADMIN_SESSION_SECRET={{APP_ADMIN_SESSION_SECRET}}
APP_SECRET_KEY={{APP_SECRET_KEY}}
APP_ADMIN_BOOTSTRAP_USERNAME={{APP_ADMIN_BOOTSTRAP_USERNAME}}
APP_ADMIN_BOOTSTRAP_PASSWORD={{APP_ADMIN_BOOTSTRAP_PASSWORD}}

# Miniflux runtime (安装器后续可自动接线，也可由 WebUI 覆盖)
APP_MINIFLUX_BASE_URL={{APP_MINIFLUX_BASE_URL}}
APP_MINIFLUX_AUTH_TOKEN={{APP_MINIFLUX_AUTH_TOKEN}}

# LLM runtime（首次安装保留为空，由 WebUI 填写）
APP_LLM_BASE_URL={{APP_LLM_BASE_URL}}
APP_LLM_API_KEY={{APP_LLM_API_KEY}}
APP_LLM_MODEL={{APP_LLM_MODEL}}
APP_LLM_FALLBACK_MODELS={{APP_LLM_FALLBACK_MODELS}}
APP_LLM_TIMEOUT_MS={{APP_LLM_TIMEOUT_MS}}

# Publish runtime
APP_PUBLISH_CHANNEL={{APP_PUBLISH_CHANNEL}}
APP_PUBLISH_HALO_BASE_URL={{APP_PUBLISH_HALO_BASE_URL}}
APP_PUBLISH_HALO_TOKEN={{APP_PUBLISH_HALO_TOKEN}}
APP_PUBLISH_OUTPUT_DIR={{APP_PUBLISH_OUTPUT_DIR}}

# PostgreSQL root
POSTGRES_ROOT_USER={{POSTGRES_ROOT_USER}}
POSTGRES_ROOT_PASSWORD={{POSTGRES_ROOT_PASSWORD}}
POSTGRES_DEFAULT_DB={{POSTGRES_DEFAULT_DB}}

# FluxDigest DB
FLUXDIGEST_DB_NAME={{FLUXDIGEST_DB_NAME}}
FLUXDIGEST_DB_USER={{FLUXDIGEST_DB_USER}}
FLUXDIGEST_DB_PASSWORD={{FLUXDIGEST_DB_PASSWORD}}

# Miniflux DB / admin
MINIFLUX_DB_NAME={{MINIFLUX_DB_NAME}}
MINIFLUX_DB_USER={{MINIFLUX_DB_USER}}
MINIFLUX_DB_PASSWORD={{MINIFLUX_DB_PASSWORD}}
MINIFLUX_ADMIN_USERNAME={{MINIFLUX_ADMIN_USERNAME}}
MINIFLUX_ADMIN_PASSWORD={{MINIFLUX_ADMIN_PASSWORD}}
MINIFLUX_API_KEY_DESCRIPTION={{MINIFLUX_API_KEY_DESCRIPTION}}

# Halo DB / admin / token bootstrap
HALO_DB_NAME={{HALO_DB_NAME}}
HALO_DB_USER={{HALO_DB_USER}}
HALO_DB_PASSWORD={{HALO_DB_PASSWORD}}
HALO_ADMIN_USERNAME={{HALO_ADMIN_USERNAME}}
HALO_ADMIN_PASSWORD={{HALO_ADMIN_PASSWORD}}
HALO_ADMIN_EMAIL={{HALO_ADMIN_EMAIL}}
HALO_PAT_NAME={{HALO_PAT_NAME}}
HALO_EXTERNAL_URL={{HALO_EXTERNAL_URL}}
