# 应用 HTTP 端口
APP_HTTP_PORT={{APP_HTTP_PORT}}

# 数据库连接配置
APP_DATABASE_NAME={{APP_DATABASE_NAME}}
APP_DATABASE_USER={{APP_DATABASE_USER}}
APP_DATABASE_PASSWORD={{APP_DATABASE_PASSWORD}}
APP_DATABASE_DSN={{APP_DATABASE_DSN}}

# Redis
APP_REDIS_ADDR={{APP_REDIS_ADDR}}

# 管理员账号（用于安装后的初始登录）
APP_ADMIN_BOOTSTRAP_USERNAME={{APP_ADMIN_BOOTSTRAP_USERNAME}}
APP_ADMIN_BOOTSTRAP_PASSWORD={{APP_ADMIN_BOOTSTRAP_PASSWORD}}

# LLM 配置（空值表示留空）
APP_LLM_BASE_URL={{APP_LLM_BASE_URL}}
APP_LLM_API_KEY={{APP_LLM_API_KEY}}
APP_LLM_MODEL={{APP_LLM_MODEL}}
APP_LLM_TIMEOUT_MS={{APP_LLM_TIMEOUT_MS}}
