CREATE ROLE {{FLUXDIGEST_DB_USER}} WITH LOGIN PASSWORD '{{FLUXDIGEST_DB_PASSWORD}}';
CREATE DATABASE {{FLUXDIGEST_DB_NAME}} OWNER {{FLUXDIGEST_DB_USER}};

CREATE ROLE {{MINIFLUX_DB_USER}} WITH LOGIN PASSWORD '{{MINIFLUX_DB_PASSWORD}}';
CREATE DATABASE {{MINIFLUX_DB_NAME}} OWNER {{MINIFLUX_DB_USER}};

CREATE ROLE {{HALO_DB_USER}} WITH LOGIN PASSWORD '{{HALO_DB_PASSWORD}}';
CREATE DATABASE {{HALO_DB_NAME}} OWNER {{HALO_DB_USER}};
