ALTER TABLE daily_digests ADD COLUMN remote_id TEXT NOT NULL DEFAULT '';
ALTER TABLE daily_digests ADD COLUMN publish_state TEXT NOT NULL DEFAULT 'failed';
ALTER TABLE daily_digests ADD COLUMN publish_error TEXT NOT NULL DEFAULT '';
ALTER TABLE daily_digests ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
